### ISSUE TITLE
[FEATURE] Have the tag above players also change

### ISSUE THREAD

**Issue by carolinaisslaying** [eclipseisoffline/customname#7] opened 2024-12-20 10:57 UTC
**Is your feature request related to a problem? Please describe.**
It is not related to a problem.

**Describe the solution you'd like, or the feature you want to see implemented**
I would like the nickname to apply not just in chat, the tab menu, but also above the player in the player tag.

**Describe alternatives you've considered**
There are no alternatives as far as I am aware.

**Additional context**
It would allow for more consistency.

**Comment by eclipseisoffline** [comment] 2024-12-20 12:15
Hello, this is a duplicate of #5. I explained in there the reasons behind why this initially wasn't added. I may add a feature like this in the future, but I've been too busy recently to get to it.

**Closed by eclipseisoffline** 2024-12-20 12:15 UTC
Labels: enhancement
